# Generated by Django 3.0.4 on 2020-03-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0002_auto_20200326_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pay', models.FloatField(default=0)),
                ('total_area', models.FloatField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alufab.customer')),
            ],
        ),
    ]
