# Generated by Django 3.0.4 on 2020-04-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0003_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='employeepayment',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='material_id',
        ),
        migrations.DeleteModel(
            name='AbsentEmp',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='employeePayment',
        ),
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.DeleteModel(
            name='materialDetails',
        ),
    ]
