# Generated by Django 3.0.6 on 2020-05-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0005_auto_20200522_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='customer',
        ),
    ]
