# Generated by Django 3.0.6 on 2020-05-22 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0006_auto_20200522_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=20)),
                ('matrial_description', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('total_amt', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alufab.customer'),
        ),
        migrations.CreateModel(
            name='Empattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Attend', models.BooleanField(default=False)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alufab.Employee')),
            ],
        ),
    ]
