# Generated by Django 3.0.6 on 2020-05-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0009_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alufab.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Ichalkaranji', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='phono',
            field=models.IntegerField(default=0),
        ),
    ]
