# Generated by Django 3.0.6 on 2020-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0011_auto_20200523_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_inventory',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
