# Generated by Django 3.0.6 on 2020-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0012_material_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leaves',
        ),
        migrations.AddField(
            model_name='employee',
            name='PAymentperday',
            field=models.FloatField(default=500),
        ),
    ]
