# Generated by Django 3.0.6 on 2020-05-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0014_auto_20200527_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PAymentperday',
            new_name='Paymentperday',
        ),
    ]
