# Generated by Django 3.0.6 on 2020-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0015_auto_20200527_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
