# Generated by Django 3.0.6 on 2020-06-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0017_auto_20200606_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_login',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
