# Generated by Django 3.0.6 on 2020-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alufab', '0019_customer_login_cust_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_inventory',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material_inventory',
            name='used',
            field=models.FloatField(default=0),
        ),
    ]
